In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")

In [2]:
dataset=pd.read_csv("CKD.csv")

In [3]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)

In [4]:
dataset

age         bp   al   su         bgr          bu        sc  \
0     2.000000  76.459948  3.0  0.0  148.112676   57.482105  3.077356   
1     3.000000  76.459948  2.0  0.0  148.112676   22.000000  0.700000   
2     4.000000  76.459948  1.0  0.0   99.000000   23.000000  0.600000   
3     5.000000  76.459948  1.0  0.0  148.112676   16.000000  0.700000   
4     5.000000  50.000000  0.0  0.0  148.112676   25.000000  0.600000   
..         ...        ...  ...  ...         ...         ...       ...   
394  51.492308  70.000000  0.0  0.0  219.000000   36.000000  1.300000   
395  51.492308  70.000000  0.0  2.0  220.000000   68.000000  2.800000   
396  51.492308  70.000000  3.0  0.0  110.000000  115.000000  6.000000   
397  51.492308  90.000000  0.0  0.0  207.000000   80.000000  6.800000   
398  51.492308  80.000000  0.0  0.0  100.000000   49.000000  1.000000   

            sod       pot       hrmo  ...  pc_normal  pcc_present  ba_present  \
0    137.528754  4.627244  12.518156  ...          0            0           0   
1    137.528754  4.627244  10.700000  ...          1            0           0   
2    138.000000  4.400000  12.000000  ...          1            0           0   
3    138.000000  3.200000   8.100000  ...          1            0           0   
4    137.528754  4.627244  11.800000  ...          1            0           0   
..          ...       ...        ...  ...        ...          ...         ...   
394  139.000000  3.700000  12.500000  ...          1            0           0   
395  137.528754  4.627244   8.700000  ...          1            0           0   
396  134.000000  2.700000   9.100000  ...          1            0           0   
397  142.000000  5.500000   8.500000  ...          1            0           0   
398  140.000000  5.000000  16.300000  ...          1            0           0   

     htn_yes  dm_yes  cad_yes  appet_yes  pe_yes  ane_yes  classification_yes  
0          0       0        0          1       1        0                   1  
1          0       0        0          1       0        0                   1  
2          0       0        0          1       0        0                   1  
3          0       0        0          1       0        1                   1  
4          0       0        0          1       0        0                   1  
..       ...     ...      ...        ...     ...      ...                 ...  
394        0       0        0          1       0        0                   1  
395        1       1        0          1       0        1                   1  
396        1       1        0          0       0        0                   1  
397        1       1        0          1       0        1                   1  
398        0       0        0          1       0        0                   0  

[399 rows x 28 columns]

In [5]:
#dataset["classification"].value_counts()

In [6]:
dataset.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')

In [7]:
independent=dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes']]

In [8]:
independent

age         bp   al   su         bgr          bu        sc  \
0     2.000000  76.459948  3.0  0.0  148.112676   57.482105  3.077356   
1     3.000000  76.459948  2.0  0.0  148.112676   22.000000  0.700000   
2     4.000000  76.459948  1.0  0.0   99.000000   23.000000  0.600000   
3     5.000000  76.459948  1.0  0.0  148.112676   16.000000  0.700000   
4     5.000000  50.000000  0.0  0.0  148.112676   25.000000  0.600000   
..         ...        ...  ...  ...         ...         ...       ...   
394  51.492308  70.000000  0.0  0.0  219.000000   36.000000  1.300000   
395  51.492308  70.000000  0.0  2.0  220.000000   68.000000  2.800000   
396  51.492308  70.000000  3.0  0.0  110.000000  115.000000  6.000000   
397  51.492308  90.000000  0.0  0.0  207.000000   80.000000  6.800000   
398  51.492308  80.000000  0.0  0.0  100.000000   49.000000  1.000000   

            sod       pot       hrmo  ...  rbc_normal  pc_normal  pcc_present  \
0    137.528754  4.627244  12.518156  ...           1          0            0   
1    137.528754  4.627244  10.700000  ...           1          1            0   
2    138.000000  4.400000  12.000000  ...           1          1            0   
3    138.000000  3.200000   8.100000  ...           1          1            0   
4    137.528754  4.627244  11.800000  ...           1          1            0   
..          ...       ...        ...  ...         ...        ...          ...   
394  139.000000  3.700000  12.500000  ...           1          1            0   
395  137.528754  4.627244   8.700000  ...           1          1            0   
396  134.000000  2.700000   9.100000  ...           1          1            0   
397  142.000000  5.500000   8.500000  ...           1          1            0   
398  140.000000  5.000000  16.300000  ...           1          1            0   

     ba_present  htn_yes  dm_yes  cad_yes  appet_yes  pe_yes  ane_yes  
0             0        0       0        0          1       1        0  
1             0        0       0        0          1       0        0  
2             0        0       0        0          1       0        0  
3             0        0       0        0          1       0        1  
4             0        0       0        0          1       0        0  
..          ...      ...     ...      ...        ...     ...      ...  
394           0        0       0        0          1       0        0  
395           0        1       1        0          1       0        1  
396           0        1       1        0          0       0        0  
397           0        1       1        0          1       0        1  
398           0        0       0        0          1       0        0  

[399 rows x 27 columns]

In [9]:
dependent=dataset[['classification_yes']]

In [10]:
dependent

classification_yes
0                     1
1                     1
2                     1
3                     1
4                     1
..                  ...
394                   1
395                   1
396                   1
397                   1
398                   0

[399 rows x 1 columns]

In [11]:
independent.shape

(399, 27)

In [12]:
dependent.shape

(399, 1)

In [13]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(independent,dependent,test_size=0.30,random_state=0)


In [14]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [15]:
from sklearn.linear_model import LogisticRegression

In [16]:
from sklearn.model_selection import GridSearchCV
param_grid={'solver': ['liblinear', 'lbfgs', 'newton-cg', 'sag', 'saga'],'penalty':['l2']}

grid=GridSearchCV(LogisticRegression(),param_grid,refit=True,verbose=3,n_jobs=-1,scoring='f1_weighted')

grid.fit(x_train,y_train)

Fitting 5 folds for each of 5 candidates, totalling 25 fits


GridSearchCV(estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'penalty': ['l2'],
                         'solver': ['liblinear', 'lbfgs', 'newton-cg', 'sag',
                                    'saga']},
             scoring='f1_weighted', verbose=3)

In [17]:
re=grid.cv_results_
grid_prediction=grid.predict(x_test)


In [18]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,grid_prediction)

In [19]:
from sklearn.metrics import classification_report
clf_report=classification_report(y_test,grid_prediction)

In [20]:
from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,grid_prediction,average="weighted")

In [21]:
print("The f1_macro value for best parameter{}:".format(grid.best_params_),f1_macro)

The f1_macro value for best parameter{'penalty': 'l2', 'solver': 'lbfgs'}: 0.9916844900066377


In [22]:
print("The confusion matrix:\n",cm)

The confusion matrix:
 [[45  0]
 [ 1 74]]


In [23]:
print("The classification report:\n",clf_report)

The classification report:
               precision    recall  f1-score   support

           0       0.98      1.00      0.99        45
           1       1.00      0.99      0.99        75

    accuracy                           0.99       120
   macro avg       0.99      0.99      0.99       120
weighted avg       0.99      0.99      0.99       120



In [24]:
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test,grid.predict_proba(x_test)[:,1])

1.0

In [25]:
table=pd.DataFrame.from_dict(re)

In [26]:
table

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_penalty  \
0       0.014250      0.000874         0.017397        0.002792            l2   
1       0.018463      0.001610         0.016993        0.000772            l2   
2       0.019253      0.004691         0.016015        0.001955            l2   
3       0.035961      0.007498         0.015385        0.001775            l2   
4       0.023483      0.004968         0.010468        0.003528            l2   

  param_solver                                    params  split0_test_score  \
0    liblinear  {'penalty': 'l2', 'solver': 'liblinear'}           0.964572   
1        lbfgs      {'penalty': 'l2', 'solver': 'lbfgs'}           0.982221   
2    newton-cg  {'penalty': 'l2', 'solver': 'newton-cg'}           0.982221   
3          sag        {'penalty': 'l2', 'solver': 'sag'}           0.982221   
4         saga       {'penalty': 'l2', 'solver': 'saga'}           0.982221   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0           0.982221           0.964572           0.964572           0.981894   
1           1.000000           0.982221           1.000000           1.000000   
2           1.000000           0.982221           1.000000           1.000000   
3           0.982221           0.982221           0.982221           1.000000   
4           0.982221           0.964572           0.982221           0.981894   

   mean_test_score  std_test_score  rank_test_score  
0         0.971566        0.008567                5  
1         0.992888        0.008710                1  
2         0.992888        0.008710                1  
3         0.985777        0.007112                3  
4         0.978626        0.007028                4

In [27]:
age_input = int(input("Age: "))
bp_input = float(input("Blood Pressure (bp): "))
al_input = int(input("Albumin (al): "))
su_input = int(input("Sugar (su): "))
bgr_input = float(input("Blood Glucose Random (bgr): "))
bu_input = float(input("Blood Urea (bu): "))
sc_input = float(input("Serum Creatinine (sc): "))
sod_input = float(input("Sodium (sod): "))
pot_input = float(input("Potassium (pot): "))
hrmo_input = float(input("Hormone Level (hrmo): "))
pcv_input = int(input("Packed Cell Volume (pcv): "))
wc_input = int(input("White Blood Cell Count (wc): "))
rc_input = float(input("Red Blood Cell Count (rc): "))


sg_b_input = int(input("Specific Gravity sg_b (0 or 1): "))
sg_c_input = int(input("Specific Gravity sg_c (0 or 1): "))
sg_d_input = int(input("Specific Gravity sg_d (0 or 1): "))
sg_e_input = int(input("Specific Gravity sg_e (0 or 1): "))
rbc_normal_input = int(input("Red Blood Cells Normal (0 or 1): "))
pc_normal_input = int(input("Pus Cells Normal (0 or 1): "))
pcc_present_input = int(input("Pus Cell Clumps Present (0 or 1): "))
ba_present_input = int(input("Bacteria Present (0 or 1): "))
htn_yes_input = int(input("Hypertension (htn_yes) (0 or 1): "))
dm_yes_input = int(input("Diabetes Mellitus (dm_yes) (0 or 1): "))
cad_yes_input = int(input("Coronary Artery Disease (cad_yes) (0 or 1): "))
appet_yes_input = int(input("Good Appetite (appet_yes) (0 or 1): "))
pe_yes_input = int(input("Pedal Edema (pe_yes) (0 or 1): "))
ane_yes_input = int(input("Anemia (ane_yes) (0 or 1): "))

Age:  45
Blood Pressure (bp):  120
Albumin (al):  2
Sugar (su):  1
Blood Glucose Random (bgr):  150
Blood Urea (bu):  40
Serum Creatinine (sc):  1.5
Sodium (sod):  135
Potassium (pot):  4.2
Hormone Level (hrmo):  1.8
Packed Cell Volume (pcv):  42
White Blood Cell Count (wc):  7500
Red Blood Cell Count (rc):  4.9
Specific Gravity sg_b (0 or 1):  0
Specific Gravity sg_c (0 or 1):  1
Specific Gravity sg_d (0 or 1):  1
Specific Gravity sg_e (0 or 1):  0
Red Blood Cells Normal (0 or 1):  0
Pus Cells Normal (0 or 1):  1
Pus Cell Clumps Present (0 or 1):  0
Bacteria Present (0 or 1):  1
Hypertension (htn_yes) (0 or 1):  0
Diabetes Mellitus (dm_yes) (0 or 1):  1
Coronary Artery Disease (cad_yes) (0 or 1):  1
Good Appetite (appet_yes) (0 or 1):  0
Pedal Edema (pe_yes) (0 or 1):  1
Anemia (ane_yes) (0 or 1):  1


In [72]:
Future_prediction=grid.predict([[age_input,bp_input,al_input,su_input,bgr_input,bu_input,sc_input,sod_input,pot_input,
                                 hrmo_input,pcv_input,wc_input,rc_input,sg_b_input,sg_c_input,sg_d_input,sg_e_input,
                                 rbc_normal_input,pc_normal_input,pcc_present_input,ba_present_input,htn_yes_input,
                                 dm_yes_input,cad_yes_input,appet_yes_input,pe_yes_input,ane_yes_input]])

In [74]:
Future_prediction

array([0])

In [76]:
import pickle

In [78]:
filename="finalaized_model_LogisticClassifier-Grid.sav"

In [80]:
pickle.dump(grid,open(filename,'wb'))

In [82]:
loaded_model=pickle.load(open("finalaized_model_LogisticClassifier-Grid.sav",'rb'))

In [99]:
result=loaded_model.predict([[45,120,2,1,150,40,1.5,135,4.2,1.8,42,7500,4.9,0,1,1,0,0,0,1,0,0,1,1,0,1,1]])

In [101]:
result

array([0])